"use client";

import { useState } from "react";
import { ChevronDown } from "lucide-react";
import { cn } from "@/lib/utils";

const FAQ_ITEMS = [
  {
    question: "What does this product actually do?",
    answer:
      "Our platform generates branded memes for your business using AI. You provide context about your brand and audience, and the system creates memes designed to drive reach and engagement on social media.",
  },
  {
    question: "Can I edit the memes myself?",
    answer:
      "Not in the current version. Every meme is generated automatically using proven templates and formats so they stay true to authentic internet meme styles.",
  },
  {
    question: "Why can’t I edit the templates?",
    answer:
      "Memes work because they follow familiar formats. Allowing unlimited editing often breaks the structure that makes a meme recognizable and shareable. By generating the meme automatically, we keep the format consistent and effective.",
  },
  {
    question: "How do you keep the memes relevant?",
    answer:
      "Our system constantly monitors the internet for new viral meme formats, trends, and cultural moments. When new templates become popular, we update the system so your memes stay current.",
  },
  {
    question: "Do you update the meme templates?",
    answer:
      "Yes. Our template library is continuously updated with new formats, fonts, and styles as meme culture evolves.",
  },
  {
    question: "Will the memes match my brand?",
    answer:
      "Yes. During onboarding we learn about your business, audience, and tone. The AI uses this context to generate memes that fit your brand rather than random internet jokes.",
  },
  {
    question: "Do you generate captions as well?",
    answer:
      "Yes. Every meme can include caption suggestions so you can publish your content quickly without needing to write social copy yourself.",
  },
  {
    question: "What platforms are these memes designed for?",
    answer:
      "Memes generated by the system are designed to work across major social platforms including Instagram, Facebook, X, LinkedIn, and TikTok-style formats.",
  },
  {
    question: "Do I need design skills to use this?",
    answer:
      "No. The system handles the design, formatting, and layout automatically so you can focus on publishing great content.",
  },
];

export function FAQSection() {
  const [openId, setOpenId] = useState<number | null>(0);

  return (
    <section
      id="faq-heading"
      aria-labelledby="faq-heading"
      className="w-full px-4 pt-16 pb-2 sm:px-6 sm:pt-20 sm:pb-4 md:px-8 md:pt-24 md:pb-6"
    >
      <h2
        id="faq-heading"
        className="text-center text-2xl font-bold text-stone-900 md:text-3xl"
      >
        Frequently asked questions
      </h2>
      <p className="marketing-copy mx-auto mt-2 max-w-xl text-center">
        Quick answers to common questions.
      </p>
      <div className="mx-auto mt-10 max-w-3xl space-y-2">
        {FAQ_ITEMS.map((item, i) => (
          <div
            key={i}
            className="rounded-xl border border-stone-200 bg-white/80 shadow-sm"
          >
            <button
              type="button"
              onClick={() => setOpenId(openId === i ? null : i)}
              className="flex w-full items-center justify-between gap-4 px-5 py-4 text-left"
              aria-expanded={openId === i}
            >
              <span className="font-medium text-stone-900">{item.question}</span>
              <ChevronDown
                className={cn(
                  "h-5 w-5 shrink-0 text-stone-500 transition-transform",
                  openId === i && "rotate-180"
                )}
              />
            </button>
            <div
              className={cn(
                "overflow-hidden transition-all",
                openId === i ? "max-h-64 opacity-100" : "max-h-0 opacity-0"
              )}
            >
              <p className="marketing-copy border-t border-stone-200 px-5 py-4 text-sm">
                {item.answer}
              </p>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}
